### ISSUE TITLE
Cannot read date/time from "timestamp" postgresql datatype

### ISSUE THREAD

**Issue by gioman** [NationalSecurityAgency/qgis-d3datavis-plugin#1]
Apparently postgresql "timestamp" columns are not read correctly and the "no valid dates found" message is returned.

**Comment by hamiltoncj** [comment]
Do you have an example data set that I can take a look at? There are so many date and time formats that I am not going to be able to support everything, but I can try to support as much as possible and document the formats that work.

**Comment by gioman** [comment]
Hi,
in this specific case could be caused by the timestamp representation in QGIS. In fact if I open a table with this datatype in PGAdmin (or if I export to CSV) the content of a cell is like

2016-06-20 08:10:00

while in QGIS is

2016-06-20T08:10:00

cheers!

**Comment by hamiltoncj** [comment]
I believe the problem is fixed. If you have the time please test it and let me know the results.

Thanks!!!

**Comment by gioman** [comment]
Fixed indeed!
