### ISSUE TITLE
GUI under Linux is not optimized.

### ISSUE THREAD

**Issue by gioman** [NationalSecurityAgency/qgis-d3datavis-plugin#2]
See the following screenshots.

![screenshot from 2016-08-04 21-37-49](https://cloud.githubusercontent.com/assets/1951107/17429298/e7bb8acc-5ae5-11e6-97c2-d1be7294519b.png)

![screenshot from 2016-08-04 21-37-54](https://cloud.githubusercontent.com/assets/1951107/17429302/eaef2442-5ae5-11e6-8e99-c1ec6f33a8b8.png)

**Comment by hamiltoncj** [comment]
Thank you for pointing this out. It made me rethink how I was designing the gui and made me learn how to use Qt Designer a little bit better. I think I now have the gui free flowing and should work with any font, but I don't have a Linux install. Could you test your linux version to see if it works properly?

Thanks!!

**Comment by gioman** [comment]
Perfect, thanks!
