### ISSUE TITLE
Summarize data values to plots

### ISSUE THREAD

**Issue by posikifi** [NationalSecurityAgency/qgis-d3datavis-plugin#5]
Hi!

I have dataset where I'd like to summarize data values to polar chart. I have undestand that now plot is just counting features per timeslot, but it will useful to have possibility summarize values from selected field.

Dataset is electricity prices in Nord Pool enviroment, you can download dataset from here: https://sahko.tk/ 

P

**Comment by hamiltoncj** [comment]
One of the fields can be a category from the data. I have been thinking about rewriting this plugin. It was one of my early plugins when I was learning QGIS plugin development. As the plugin stands right now, I don't plan on making any changes, but if I decided to rewrite it, then I would make it more flexible.

**Comment by posikifi** [comment]
Ok, I see. I do hope you will rewrite this. Thank you for all NSA related plugins!
