### ISSUE TITLE
The _imaging C module is not installed when running Word Cloud from Attribute

### ISSUE THREAD

**Issue by kowalski93** [NationalSecurityAgency/qgis-d3datavis-plugin#6]
On QGIS 3.28 stable, when running Word Cloud from Attribute, I get:
ImportError: The _imaging C module is not installed
To solve this, I uninstall Pillow and install version 10.0.0 from OSGeo4W Shell:
`pip uninstall Pillow`
`pip install Pillow==10.0.0`

**Comment by hamiltoncj** [comment]
Yup. I mention this problem in the documentation and the fix is basically what you mentioned. I don't think you need to specify the version. There is not a whole lot I can do about this other than to mention the fix that is required.
